url: https://schoolhouselabs.github.io

# Site settings
title: Schoolhouse Labs
email: schoolhouselabs@gmail.com
description: "Software consultancy helping teacher entrepreneurs and schools get their ideas into the classroom."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Landon Marder
  pic: 1
  position: Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #
#
# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/schoolhouselabs
  - title: facebook
    url:
  - title: github
    url: http://github.com/schoolhouselabs

# Postal address (add as many lines as necessary)
address:
  - line: Schoolhouse Labs
  - line: Brooklyn, NY 11238

# Build settings
markdown: kramdown
permalink: pretty
